SELECT
NEIGHBOURHOODS.Neighbourhood,
EDUCATIONSTATISTICS.PassRateOSSLT,
SCHOOLS.Name AS SchoolName,
LIBRARIES.BranchName,
SCHOOLS.Shape.STDistance(LIBRARIES.Shape) * 111300 AS DistanceToLibrary

FROM EDUCATIONSTATISTICS
INNER JOIN NEIGHBOURHOODS ON NEIGHBOURHOODS.NeighbourhoodID = EDUCATIONSTATISTICS.NeighbourhoodID
LEFT JOIN SCHOOLS ON NEIGHBOURHOODS.NeighbourhoodID = SCHOOLS.NeighbourhoodID
LEFT JOIN LIBRARIES ON NEIGHBOURHOODS.NeighbourhoodID = LIBRARIES.NeighbourhoodID

WHERE EDUCATIONSTATISTICS.PassRateOSSLT < 60;
