SELECT 
SCHOOLS.Name AS SchoolName, 
COUNT(RECREATIONFACILITIES.Shape) AS RecreationFacilityCount 

FROM SCHOOLS, RECREATIONFACILITIES 

WHERE 
SCHOOLS.Shape.STBuffer(0.009).STIntersects(RECREATIONFACILITIES.Shape) = 1 

GROUP BY SCHOOLS.Name;
